module.exports = [
  {"id":"1", "name":"Ambarawa"},
  {"id":"2", "name":"Ambon"},
  {"id":"3", "name":"Amlapura"},
  {"id":"4", "name":"Amuntai"},
  {"id":"5", "name":"Argamakmur"},
  {"id":"6", "name":"Atambua"},
  {"id":"7", "name":"Babo"},
  {"id":"8", "name":"Bagan Siapiapi"},
  {"id":"9", "name":"Bajawa"},
  {"id":"10", "name":"Balige"},
  {"id":"11", "name":"Balik Papan"},
  {"id":"12", "name":"Banda Aceh"},
  {"id":"13", "name":"Bandarlampung"},
  {"id":"14", "name":"Bandung"},
  {"id":"15", "name":"Bangkalan"},
  {"id":"16", "name":"Bangkinang"},
  {"id":"17", "name":"Bangko"},
  {"id":"18", "name":"Bangli"},
  {"id":"19", "name":"Banjar"},
  {"id":"20", "name":"Banjar Baru"},
  {"id":"21", "name":"Banjarmasin"},
  {"id":"22", "name":"Banjarnegara"},
  {"id":"23", "name":"Bantaeng"},
  {"id":"24", "name":"Banten"},
  {"id":"25", "name":"Bantul"},
  {"id":"26", "name":"Banyuwangi"},
  {"id":"27", "name":"Barabai"},
  {"id":"28", "name":"Barito"},
  {"id":"29", "name":"Barru"},
  {"id":"30", "name":"Batam"},
  {"id":"31", "name":"Batang"},
  {"id":"32", "name":"Batu"},
  {"id":"33", "name":"Baturaja"},
  {"id":"34", "name":"Batusangkar"},
  {"id":"35", "name":"Baubau"},
  {"id":"36", "name":"Bekasi"},
  {"id":"37", "name":"Bengkalis"},
  {"id":"38", "name":"Bengkulu"},
  {"id":"39", "name":"Benteng"},
  {"id":"40", "name":"Biak"},
  {"id":"41", "name":"Bima"},
  {"id":"42", "name":"Binjai"},
  {"id":"43", "name":"Bireuen"},
  {"id":"44", "name":"Bitung"},
  {"id":"45", "name":"Blitar"},
  {"id":"46", "name":"Blora"},
  {"id":"47", "name":"Bogor"},
  {"id":"48", "name":"Bojonegoro"},
  {"id":"49", "name":"Bondowoso"},
  {"id":"50", "name":"Bontang"},
  {"id":"51", "name":"Boyolali"},
  {"id":"52", "name":"Brebes"},
  {"id":"53", "name":"Bukit Tinggi"},
  {"id":"54", "name":"Bulukumba"},
  {"id":"55", "name":"Buntok"},
  {"id":"56", "name":"Cepu"},
  {"id":"57", "name":"Ciamis"},
  {"id":"58", "name":"Cianjur"},
  {"id":"59", "name":"Cibinong"},
  {"id":"60", "name":"Cilacap"},
  {"id":"61", "name":"Cilegon"},
  {"id":"62", "name":"Cimahi"},
  {"id":"63", "name":"Cirebon"},
  {"id":"64", "name":"Curup"},
  {"id":"65", "name":"Demak"},
  {"id":"66", "name":"Denpasar"},
  {"id":"67", "name":"Depok"},
  {"id":"68", "name":"Dili"},
  {"id":"69", "name":"Dompu"},
  {"id":"70", "name":"Donggala"},
  {"id":"71", "name":"Dumai"},
  {"id":"72", "name":"Ende"},
  {"id":"73", "name":"Enggano"},
  {"id":"74", "name":"Enrekang"},
  {"id":"75", "name":"Fakfak"},
  {"id":"76", "name":"Garut"},
  {"id":"77", "name":"Gianyar"},
  {"id":"78", "name":"Gombong"},
  {"id":"79", "name":"Gorontalo"},
  {"id":"80", "name":"Gresik"},
  {"id":"81", "name":"Gunung Sitoli"},
  {"id":"82", "name":"Indramayu"},
  {"id":"83", "name":"Jakarta"},
  {"id":"84", "name":"Jambi"},
  {"id":"85", "name":"Jayapura"},
  {"id":"86", "name":"Jember"},
  {"id":"87", "name":"Jeneponto"},
  {"id":"88", "name":"Jepara"},
  {"id":"89", "name":"Jombang"},
  {"id":"90", "name":"Kabanjahe"},
  {"id":"91", "name":"Kalabahi"},
  {"id":"92", "name":"Kalianda"},
  {"id":"93", "name":"Kandangan"},
  {"id":"309", "name":"Karanganyar"},
  {"id":"94", "name":"Karanganyar Kebumen"},
  {"id":"95", "name":"Karawang"},
  {"id":"96", "name":"Kasungan"},
  {"id":"97", "name":"Kayuagung"},
  {"id":"98", "name":"Kebumen"},
  {"id":"99", "name":"Kediri"},
  {"id":"100", "name":"Kefamenanu"},
  {"id":"101", "name":"Kendal"},
  {"id":"102", "name":"Kendari"},
  {"id":"103", "name":"Kertosono"},
  {"id":"104", "name":"Ketapang"},
  {"id":"105", "name":"Kisaran"},
  {"id":"106", "name":"Klaten"},
  {"id":"107", "name":"Kolaka"},
  {"id":"108", "name":"Kota Baru Pulau Laut"},
  {"id":"109", "name":"Kota Bumi"},
  {"id":"110", "name":"Kota Jantho"},
  {"id":"111", "name":"Kota Mobagu"},
  {"id":"112", "name":"Kuala Kapuas"},
  {"id":"113", "name":"Kuala Kurun"},
  {"id":"114", "name":"Kuala Pembuang"},
  {"id":"115", "name":"Kuala Tungkal"},
  {"id":"116", "name":"Kudus"},
  {"id":"117", "name":"Kuningan"},
  {"id":"118", "name":"Kupang"},
  {"id":"119", "name":"Kutacane"},
  {"id":"120", "name":"Kutoarjo"},
  {"id":"121", "name":"Labuhan"},
  {"id":"122", "name":"Lahat"},
  {"id":"123", "name":"Lamongan"},
  {"id":"124", "name":"Langsa"},
  {"id":"125", "name":"Larantuka"},
  {"id":"126", "name":"Lawang"},
  {"id":"127", "name":"Lhoseumawe"},
  {"id":"128", "name":"Limboto"},
  {"id":"129", "name":"Lubuk Basung"},
  {"id":"130", "name":"Lubuk Linggau"},
  {"id":"131", "name":"Lubuk Pakam"},
  {"id":"132", "name":"Lubuk Sikaping"},
  {"id":"133", "name":"Lumajang"},
  {"id":"134", "name":"Luwuk"},
  {"id":"135", "name":"Madiun"},
  {"id":"136", "name":"Magelang"},
  {"id":"137", "name":"Magetan"},
  {"id":"138", "name":"Majalengka"},
  {"id":"139", "name":"Majene"},
  {"id":"140", "name":"Makale"},
  {"id":"141", "name":"Makassar"},
  {"id":"142", "name":"Malang"},
  {"id":"143", "name":"Mamuju"},
  {"id":"144", "name":"Manna"},
  {"id":"145", "name":"Manokwari"},
  {"id":"146", "name":"Marabahan"},
  {"id":"147", "name":"Maros"},
  {"id":"148", "name":"Martapura"},
  {"id":"149", "name":"Masohi"},
  {"id":"150", "name":"Mataram"},
  {"id":"151", "name":"Maumere"},
  {"id":"152", "name":"Medan"},
  {"id":"153", "name":"Mempawah"},
  {"id":"154", "name":"Menado"},
  {"id":"155", "name":"Mentok"},
  {"id":"156", "name":"Merauke"},
  {"id":"157", "name":"Metro"},
  {"id":"158", "name":"Meulaboh"},
  {"id":"159", "name":"Mojokerto"},
  {"id":"160", "name":"Muara Bulian"},
  {"id":"161", "name":"Muara Bungo"},
  {"id":"162", "name":"Muara Enim"},
  {"id":"163", "name":"Muara Teweh"},
  {"id":"164", "name":"Muaro Sijunjung"},
  {"id":"165", "name":"Muntilan"},
  {"id":"166", "name":"Nabire"},
  {"id":"167", "name":"Negara"},
  {"id":"168", "name":"Nganjuk"},
  {"id":"169", "name":"Ngawi"},
  {"id":"170", "name":"Nunukan"},
  {"id":"171", "name":"Pacitan"},
  {"id":"172", "name":"Padang"},
  {"id":"173", "name":"Padang Panjang"},
  {"id":"174", "name":"Padang Sidempuan"},
  {"id":"175", "name":"Pagaralam"},
  {"id":"176", "name":"Painan"},
  {"id":"177", "name":"Palangkaraya"},
  {"id":"178", "name":"Palembang"},
  {"id":"179", "name":"Palopo"},
  {"id":"180", "name":"Palu"},
  {"id":"181", "name":"Pamekasan"},
  {"id":"182", "name":"Pandeglang"},
  {"id":"183", "name":"Pangkajene"},
  {"id":"184", "name":"Pangkajene Sidenreng"},
  {"id":"185", "name":"Pangkalanbun"},
  {"id":"186", "name":"Pangkalpinang"},
  {"id":"187", "name":"Panyabungan"},
  {"id":"188", "name":"Pare"},
  {"id":"189", "name":"Parepare"},
  {"id":"190", "name":"Pariaman"},
  {"id":"191", "name":"Pasuruan"},
  {"id":"192", "name":"Pati"},
  {"id":"193", "name":"Payakumbuh"},
  {"id":"194", "name":"Pekalongan"},
  {"id":"195", "name":"Pekan Baru"},
  {"id":"196", "name":"Pemalang"},
  {"id":"197", "name":"Pematangsiantar"},
  {"id":"198", "name":"Pendopo"},
  {"id":"199", "name":"Pinrang"},
  {"id":"200", "name":"Pleihari"},
  {"id":"201", "name":"Polewali"},
  {"id":"202", "name":"Pondok Gede"},
  {"id":"203", "name":"Ponorogo"},
  {"id":"204", "name":"Pontianak"},
  {"id":"205", "name":"Poso"},
  {"id":"206", "name":"Prabumulih"},
  {"id":"207", "name":"Praya"},
  {"id":"208", "name":"Probolinggo"},
  {"id":"209", "name":"Purbalingga"},
  {"id":"210", "name":"Purukcahu"},
  {"id":"211", "name":"Purwakarta"},
  {"id":"212", "name":"Purwodadigrobogan"},
  {"id":"213", "name":"Purwokerto"},
  {"id":"214", "name":"Purworejo"},
  {"id":"215", "name":"Putussibau"},
  {"id":"216", "name":"Raha"},
  {"id":"217", "name":"Rangkasbitung"},
  {"id":"218", "name":"Rantau"},
  {"id":"219", "name":"Rantauprapat"},
  {"id":"220", "name":"Rantepao"},
  {"id":"221", "name":"Rembang"},
  {"id":"222", "name":"Rengat"},
  {"id":"223", "name":"Ruteng"},
  {"id":"224", "name":"Sabang"},
  {"id":"225", "name":"Salatiga"},
  {"id":"226", "name":"Samarinda"},
  {"id":"227", "name":"Sampang"},
  {"id":"228", "name":"Sampit"},
  {"id":"229", "name":"Sanggau"},
  {"id":"230", "name":"Sawahlunto"},
  {"id":"231", "name":"Sekayu"},
  {"id":"232", "name":"Selong"},
  {"id":"233", "name":"Semarang"},
  {"id":"234", "name":"Sengkang"},
  {"id":"235", "name":"Serang"},
  {"id":"236", "name":"Serui"},
  {"id":"237", "name":"Sibolga"},
  {"id":"238", "name":"Sidikalang"},
  {"id":"239", "name":"Sidoarjo"},
  {"id":"240", "name":"Sigli"},
  {"id":"241", "name":"Singaparna"},
  {"id":"242", "name":"Singaraja"},
  {"id":"243", "name":"Singkawang"},
  {"id":"244", "name":"Sinjai"},
  {"id":"245", "name":"Sintang"},
  {"id":"246", "name":"Situbondo"},
  {"id":"247", "name":"Slawi"},
  {"id":"248", "name":"Sleman"},
  {"id":"249", "name":"Soasiu"},
  {"id":"250", "name":"Soe"},
  {"id":"251", "name":"Solo"},
  {"id":"252", "name":"Solok"},
  {"id":"253", "name":"Soreang"},
  {"id":"254", "name":"Sorong"},
  {"id":"255", "name":"Sragen"},
  {"id":"256", "name":"Stabat"},
  {"id":"257", "name":"Subang"},
  {"id":"258", "name":"Sukabumi"},
  {"id":"259", "name":"Sukoharjo"},
  {"id":"260", "name":"Sumbawa Besar"},
  {"id":"261", "name":"Sumedang"},
  {"id":"262", "name":"Sumenep"},
  {"id":"263", "name":"Sungai Liat"},
  {"id":"264", "name":"Sungai Penuh"},
  {"id":"265", "name":"Sungguminasa"},
  {"id":"266", "name":"Surabaya"},
  {"id":"267", "name":"Surakarta"},
  {"id":"268", "name":"Tabanan"},
  {"id":"269", "name":"Tahuna"},
  {"id":"270", "name":"Takalar"},
  {"id":"271", "name":"Takengon"},
  {"id":"272", "name":"Tamiang Layang"},
  {"id":"273", "name":"Tanah Grogot"},
  {"id":"274", "name":"Tangerang"},
  {"id":"275", "name":"Tanjung Balai"},
  {"id":"276", "name":"Tanjung Enim"},
  {"id":"277", "name":"Tanjung Pandan"},
  {"id":"278", "name":"Tanjung Pinang"},
  {"id":"279", "name":"Tanjung Redep"},
  {"id":"280", "name":"Tanjung Selor"},
  {"id":"281", "name":"Tapak Tuan"},
  {"id":"282", "name":"Tarakan"},
  {"id":"283", "name":"Tarutung"},
  {"id":"284", "name":"Tasikmalaya"},
  {"id":"285", "name":"Tebing Tinggi"},
  {"id":"286", "name":"Tegal"},
  {"id":"287", "name":"Temanggung"},
  {"id":"288", "name":"Tembilahan"},
  {"id":"289", "name":"Tenggarong"},
  {"id":"290", "name":"Ternate"},
  {"id":"291", "name":"Tolitoli"},
  {"id":"292", "name":"Tondano"},
  {"id":"293", "name":"Trenggalek"},
  {"id":"294", "name":"Tual"},
  {"id":"295", "name":"Tuban"},
  {"id":"296", "name":"Tulung Agung"},
  {"id":"297", "name":"Ujung Berung"},
  {"id":"298", "name":"Ungaran"},
  {"id":"299", "name":"Waikabubak"},
  {"id":"300", "name":"Waingapu"},
  {"id":"301", "name":"Wamena"},
  {"id":"302", "name":"Watampone"},
  {"id":"303", "name":"Watansoppeng"},
  {"id":"304", "name":"Wates"},
  {"id":"305", "name":"Wonogiri"},
  {"id":"306", "name":"Wonosari"},
  {"id":"307", "name":"Wonosobo"},
  {"id":"308", "name":"Yogyakarta"}
];
